// ARI用語集データ

export type Term = {
  id: string
  term: string
  reading?: string
  category: string
  description: string
  awsExam: boolean
  examPoint?: string
}

export const CATEGORIES = [
  'ビジネス・プロジェクト運営',
  '営業・マーケティング',
  '契約・法務',
  'IT全般・インフラ',
  'クラウド（AWS / GCP）',
  '開発・アプリケーション基盤',
  'データ分析・BI・データベース',
  'AI・生成AI関連',
] as const

// フィルターチップ用の短縮名
export const CATEGORY_LABELS: Record<string, string> = {
  'ビジネス・プロジェクト運営': 'ビジネス',
  '営業・マーケティング': '営業',
  '契約・法務': '契約',
  'IT全般・インフラ': 'IT',
  'クラウド（AWS / GCP）': 'クラウド',
  '開発・アプリケーション基盤': '開発',
  'データ分析・BI・データベース': 'データ',
  'AI・生成AI関連': 'AI',
}

// カテゴリバッジのカラー（インラインスタイル用）
export const CATEGORY_COLORS: Record<string, { bg: string; text: string }> = {
  'ビジネス・プロジェクト運営': { bg: '#dbeafe', text: '#1e40af' },
  '営業・マーケティング': { bg: '#ede9fe', text: '#6b21a8' },
  '契約・法務': { bg: '#ffedd5', text: '#9a3412' },
  'IT全般・インフラ': { bg: '#dcfce7', text: '#166534' },
  'クラウド（AWS / GCP）': { bg: '#e0f2fe', text: '#0c4a6e' },
  '開発・アプリケーション基盤': { bg: '#ccfbf1', text: '#134e4a' },
  'データ分析・BI・データベース': { bg: '#fef9c3', text: '#713f12' },
  'AI・生成AI関連': { bg: '#ffe4e6', text: '#9f1239' },
}

export const terms: Term[] = [
  // ── 1. ビジネス・プロジェクト運営 ──────────────────────────────
  {
    id: 'b1',
    term: 'ケーパビリティ',
    reading: 'けーぱびりてぃ',
    category: 'ビジネス・プロジェクト運営',
    description: '組織の強み・能力のこと。「わが社のケーパビリティを活かす」のように使う。',
    awsExam: false,
  },
  {
    id: 'b2',
    term: 'BP（ビジネスパートナー）',
    reading: 'びーぴー',
    category: 'ビジネス・プロジェクト運営',
    description: '業務委託先や協業先を指す。「BPさんにお願いしている」などの使い方。',
    awsExam: false,
  },
  {
    id: 'b3',
    term: '座組（ざぐみ）',
    reading: 'ざぐみ',
    category: 'ビジネス・プロジェクト運営',
    description: 'もともと演劇の言葉。ビジネスでは「プロジェクトの体制・メンバー構成」を指す。自社・協力会社・クライアントの誰がどの役割で関わるかという「座席表」のようなもの。\n\n例：「今回のプロジェクト、座組が少し弱いですね（＝適切なスキルを持つ人が足りない）」',
    awsExam: false,
  },
  {
    id: 'b4',
    term: '頭出し',
    reading: 'あたまだし',
    category: 'ビジネス・プロジェクト運営',
    description: '①事前共有・根回し：本格的な提案や会議の前に、さわりだけ伝えておくこと。\n②冒頭の要旨説明：会議の冒頭で「本日の論点は〇点です」と全体像を提示すること。\n\n例：「本件、部長に頭出ししておきました（＝事前に軽く伝えて反応を見た）」',
    awsExam: false,
  },
  {
    id: 'b5',
    term: 'トレードオフ',
    reading: 'とれーどおふ',
    category: 'ビジネス・プロジェクト運営',
    description: '一方を立てれば他方が立たない関係。例：確実性と処理速度のトレードオフ、コストと品質のバランス。',
    awsExam: false,
  },
  {
    id: 'b6',
    term: 'リビール（Reveal）',
    reading: 'りびーる',
    category: 'ビジネス・プロジェクト運営',
    description: '明らかにする、公開する。プレゼンや提案で「今まで隠していた情報を見せる」ときに使う。',
    awsExam: false,
  },
  {
    id: 'b7',
    term: 'RACI（レイシー）',
    reading: 'れいしー',
    category: 'ビジネス・プロジェクト運営',
    description: '役割分担を整理するフレームワーク。\n\nR（Responsible）：実作業の実行責任者\nA（Accountable）：最終的な成果責任者・承認者\nC（Consulted）：相談・意見提供者（双方向）\nI（Informed）：結果報告を受ける立場（片方向）',
    awsExam: false,
  },
  {
    id: 'b8',
    term: 'QCDS',
    reading: 'きゅーしーでぃーえす',
    category: 'ビジネス・プロジェクト運営',
    description: 'プロジェクト管理の4つの観点。\n\nQ：Quality（品質）\nC：Cost（コスト）\nD：Delivery（納期）\nS：Safety（安全）',
    awsExam: false,
  },
  {
    id: 'b9',
    term: 'ROI（アールオーアイ）',
    reading: 'あーるおーあい',
    category: 'ビジネス・プロジェクト運営',
    description: 'Return On Investment。投資利益率・投資収益率のこと。「この投資でどれだけ儲かるか」を示す指標。',
    awsExam: false,
  },
  {
    id: 'b10',
    term: 'FTE（Full-Time Equivalent）',
    reading: 'えふてぃーいー',
    category: 'ビジネス・プロジェクト運営',
    description: '常勤換算・フルタイム等量。頭数ではなく、フルタイム社員何人分の仕事量かを測る指標。パートタイムや複数人が関わる仕事量を統一基準で表す。',
    awsExam: false,
  },
  {
    id: 'b11',
    term: 'イシュー（Issue）',
    reading: 'いしゅー',
    category: 'ビジネス・プロジェクト運営',
    description: '「今、本当に解決すべき本質的な課題」のこと。\n\n問題（Problem）：目に見えている困った事象（例：売上が落ちている）\nイシュー（Issue）：「なぜ売上が落ちているのか？どこに手を打てば劇的に改善するか？」という議論して結論を出すべき核心部分。',
    awsExam: false,
  },

  // ── 2. 営業・マーケティング ──────────────────────────────
  {
    id: 's1',
    term: '予材（よざい）',
    reading: 'よざい',
    category: '営業・マーケティング',
    description: '「予定材料」の略。契約には至っていないが今後受注できる可能性がある案件のタネ。目標金額の2〜3倍の予材を常に積み上げておくマネジメント手法（予材管理）が有名。',
    awsExam: false,
  },
  {
    id: 's2',
    term: 'PPL（Pipeline）',
    reading: 'ぱいぷらいん',
    category: '営業・マーケティング',
    description: '営業や事業管理で使う言葉で、「将来の売上につながる見込み案件の集合」。案件の流れをパイプライン（水道管）に例えた表現。',
    awsExam: false,
  },
  {
    id: 's3',
    term: 'フォーキャストシート',
    reading: 'ふぉーきゃすとしーと',
    category: '営業・マーケティング',
    description: '将来の売上・利益・コストなどを予測するための表（シート）。営業では案件ごとの受注確度と金額を整理するために使う。',
    awsExam: false,
  },
  {
    id: 's4',
    term: 'SFシート',
    reading: 'えすえふしーと',
    category: '営業・マーケティング',
    description: 'Salesforce（営業管理ツール）で管理する案件シート。案件の状況・金額・確度・担当者などを記録する。',
    awsExam: false,
  },
  {
    id: 's5',
    term: 'プライシング',
    reading: 'ぷらいしんぐ',
    category: '営業・マーケティング',
    description: '価格設定・価格戦略のこと。「このサービスをいくらで売るか」を決める行為やその戦略全般を指す。',
    awsExam: false,
  },
  {
    id: 's6',
    term: 'LP（ランディングページ）',
    reading: 'えるぴー',
    category: '営業・マーケティング',
    description: '「1枚完結」の縦長のWebページ。広告からユーザーが最初に到達するページで、商品やサービスの訴求に特化したページ。',
    awsExam: false,
  },
  {
    id: 's7',
    term: 'USP（Unique Selling Proposition）',
    reading: 'ゆーえすぴー',
    category: '営業・マーケティング',
    description: '「独自の強み」「他社にはない売り」。競合と差別化できる自社だけの価値提案のこと。',
    awsExam: false,
  },
  {
    id: 's8',
    term: 'STP分析',
    reading: 'えすてぃーぴーぶんせき',
    category: '営業・マーケティング',
    description: 'マーケティング戦略の基本フレームワーク。\n\nS（Segmentation）：市場を似たニーズを持つ顧客グループに分ける\nT（Targeting）：勝負する領域を絞る\nP（Positioning）：自社製品の独自ポジションを築く',
    awsExam: false,
  },
  {
    id: 's9',
    term: 'ペルソナ分析 / ファン・ペルソナ',
    reading: 'ぺるそなぶんせき',
    category: '営業・マーケティング',
    description: 'ブランドを熱狂的に支持してくれるファン（優良顧客）に焦点を当てた分析。一般的なペルソナ設定よりさらに踏み込んで、理想の顧客像を具体化する。',
    awsExam: false,
  },
  {
    id: 's10',
    term: 'UGC（User Generated Content）キュレーション',
    reading: 'ゆーじーしー',
    category: '営業・マーケティング',
    description: 'ユーザーが作成したコンテンツ（口コミ・レビュー・SNS投稿）を収集・整理して活用する手法。ファン・ペルソナ分析で特定した熱狂的ファンの声を広げていく。',
    awsExam: false,
  },
  {
    id: 's11',
    term: 'LTV予測',
    reading: 'えるてぃーぶいよそく',
    category: '営業・マーケティング',
    description: 'Life Time Value（顧客生涯価値）予測。一人の顧客が取引期間全体を通じて企業にもたらす総収益の予測値。',
    awsExam: false,
  },
  {
    id: 's12',
    term: 'MAシナリオ',
    reading: 'えむえーしなりお',
    category: '営業・マーケティング',
    description: 'マーケティング・オートメーションの設計図。MAツール（Salesforce Marketing Cloud、HubSpotなど）を使い、「いつ」「誰に」「何を」「どうやって」届けるかを設計した自動コミュニケーションの流れ。',
    awsExam: false,
  },
  {
    id: 's13',
    term: 'リバー・サンプリング（River Sampling）',
    reading: 'りばーさんぷりんぐ',
    category: '営業・マーケティング',
    description: '市場調査や広告配信のターゲット選定で使われる手法。川の流れのように次々と流れてくる対象者から一定の割合でサンプルを抽出する。',
    awsExam: false,
  },
  {
    id: 's14',
    term: 'BANTC（バントシー）',
    reading: 'ばんとしー',
    category: '営業・マーケティング',
    description: '法人営業で見込み客の確度を判断するヒアリングフレームワーク。\n\nB（Budget）：予算は確保されているか？\nA（Authority）：決裁権者は誰か？\nN（Needs）：必要とする課題があるか？\nT（Timeframe）：導入時期の期限は？\nC（Competitor）：競合他社と比較検討しているか？',
    awsExam: false,
  },
  {
    id: 's15',
    term: 'SPIN手法',
    reading: 'すぴんしゅほう',
    category: '営業・マーケティング',
    description: '売り込むのではなく、質問を通じて相手自身に課題を気づかせる営業手法。\n\nS（Situation）：状況把握\nP（Problem）：問題・不満の明確化\nI（Implication）：問題の影響を深掘りして示唆\nN（Need-payoff）：解決後の理想を描かせる',
    awsExam: false,
  },
  {
    id: 's16',
    term: 'GDPR',
    reading: 'じーでぃーぴーあーる',
    category: '営業・マーケティング',
    description: 'General Data Protection Regulation。EU域内の個人データ保護を目的とした法律。EU内に居住する個人のデータを扱う場合、日本企業でも適用される「域外適用」があるのが特徴。',
    awsExam: false,
  },

  // ── 3. 契約・法務 ──────────────────────────────
  {
    id: 'c1',
    term: '善管注意義務',
    reading: 'ぜんかんちゅういぎむ',
    category: '契約・法務',
    description: '善良な管理者の注意義務。準委任でも派遣契約でも発生する。プロとしての水準で業務を行う義務。注意が必要。',
    awsExam: false,
  },
  {
    id: 'c2',
    term: '履行割合型',
    reading: 'りこうわりあいがた',
    category: '契約・法務',
    description: '準委任契約の報酬形態の一つ。作業の進捗（履行割合）に応じて報酬が発生する。ひな形として参照するケースが多い。',
    awsExam: false,
  },
  {
    id: 'c3',
    term: '契約不適合責任（旧・瑕疵担保責任）',
    reading: 'けいやくふてきごうせきにん',
    category: '契約・法務',
    description: '成果物が契約内容に適合していない場合の売主・請負人の責任。不適合を知ってから1年以内に通知が必要。権利は引き渡し時から10年（短縮可）。旧称：瑕疵担保責任。',
    awsExam: false,
  },
  {
    id: 'c4',
    term: '著作権',
    reading: 'ちょさくけん',
    category: '契約・法務',
    description: '成果物の権利帰属の確認が重要。制作したシステムやドキュメントの著作権が誰に帰属するかを契約書で明記しておく必要がある。',
    awsExam: false,
  },

  // ── 4. IT全般・インフラ ──────────────────────────────
  {
    id: 'i1',
    term: 'RPG',
    reading: 'あーるぴーじー',
    category: 'IT全般・インフラ',
    description: 'IBMのAS/400（オフコン・オフィスコンピュータ）で使われた独自のプログラミング言語。レガシーシステムでよく登場する。ロールプレイングゲームとは別物。',
    awsExam: false,
  },
  {
    id: 'i2',
    term: 'MFA認証（Multi-Factor Authentication）',
    reading: 'えむえふえー にんしょう',
    category: 'IT全般・インフラ',
    description: '多要素認証。パスワードに加えてスマホ認証コードや生体認証など、2つ以上の要素でログインする仕組み。ITセキュリティ・AWS・BIツールのログインで必須。',
    awsExam: true,
    examPoint: 'セキュリティのベストプラクティス。特にルートアカウントには必ず設定すること。「最小権限の原則」と合わせて覚える。',
  },
  {
    id: 'i3',
    term: 'SMO（Service Management Office）',
    reading: 'えすえむおー',
    category: 'IT全般・インフラ',
    description: '組織全体のITサービス品質やルールを横断的に管理・最適化する専門部署（または機能）。ITSMを組織として推進する役割を担う。',
    awsExam: false,
  },
  {
    id: 'i4',
    term: 'ITSM（IT Service Management）',
    reading: 'あいてぃーえすえむ',
    category: 'IT全般・インフラ',
    description: 'ITシステムを「単なる機械」ではなく、ユーザーに価値を届ける「サービス」として管理・運用する考え方。「ITを止まらないよう運用するための管理の仕組み」。',
    awsExam: false,
  },
  {
    id: 'i5',
    term: 'Amazon Connect（あまこね）',
    reading: 'あまぞんこねくと',
    category: 'IT全般・インフラ',
    description: 'AWS上のクラウド型電話交換機（PBX）／コールセンター基盤。従来の物理的なコールセンター設備を不要にし、クラウドで電話・チャット対応を実現するサービス。',
    awsExam: true,
    examPoint: 'AWSが提供するクラウド型コンタクトセンターサービス。使った分だけ課金（従量課金）が特徴。',
  },
  {
    id: 'i6',
    term: 'Apache JMeter（アパッチ・ジェイメーター）',
    reading: 'じぇいめーたー',
    category: 'IT全般・インフラ',
    description: '負荷テストツール。Webサービスに大量のアクセスを模擬して性能を測定する。AWSが提供する負荷テストソリューションの中でエンジンの役割として使われている。',
    awsExam: false,
  },

  // ── 5. クラウド（AWS / GCP） ──────────────────────────────
  {
    id: 'a1',
    term: 'AWS Organizations（オーガナイゼーション）',
    reading: 'おーがないぜーしょん',
    category: 'クラウド（AWS / GCP）',
    description: '複数のAWSアカウントを一つのグループとしてまとめて管理できるサービス。\n\n主な機能：\n・一括請求（コンソリデーティッド・ビリング）\n・アカウントのガバナンス管理\n・アカウント作成の簡素化\n※追加料金なし',
    awsExam: true,
    examPoint: 'キーワード：「複数アカウント管理」「一括請求」「SCP（サービスコントロールポリシー）」「OU（組織単位）」',
  },
  {
    id: 'a2',
    term: 'リザーブドインスタンス（RI）',
    reading: 'りざーぶどいんすたんす',
    category: 'クラウド（AWS / GCP）',
    description: '長期間（1年または3年）使うことを約束することで、料金が大幅に割引されるAWSの予約制度。オンデマンド料金と比べて最大72%割引になる。EC2やRDSで利用可能。',
    awsExam: true,
    examPoint: 'コスト最適化の代表的な選択肢。「長期利用確約＝割引」が基本。Savings Plansとの違いも確認。',
  },
  {
    id: 'a3',
    term: 'AWS Lambda（ラムダ）',
    reading: 'らむだ',
    category: 'クラウド（AWS / GCP）',
    description: 'サーバーを用意しなくてもコードを実行できるサーバーレスサービス。イベント（トリガー）に応じて自動起動し、実行時間だけ課金される。データベース操作や自動化処理によく使われる。',
    awsExam: true,
    examPoint: 'キーワード：「サーバーレス」「イベント駆動」「実行時間課金」「最大15分」。EC2との違いを理解する。',
  },
  {
    id: 'a4',
    term: 'AWS Bedrock（ベッドロック）',
    reading: 'べっどろっく',
    category: 'クラウド（AWS / GCP）',
    description: 'AWSが提供する「最新のAIを簡単・安全にビジネスで使うためのサービス」。フルマネージド型で基盤モデルをAPI経由で利用できる。\n\n利用できる主なAI：\n・Claude（Anthropic）\n・Llama（Meta）\n・Stable Diffusion（Stability AI）\n・Amazon Titan',
    awsExam: true,
    examPoint: 'キーワード：「フルマネージド」「基盤モデル」「API」。AI/MLドメインの代表的サービス。',
  },
  {
    id: 'a5',
    term: 'GCP（Google Cloud Platform）',
    reading: 'じーしーぴー',
    category: 'クラウド（AWS / GCP）',
    description: 'Googleが提供するクラウドサービスの総称（現：Google Cloud）。\n\n代表サービス：\n・GKE（Google Kubernetes Engine）：コンテナを動かす司令塔\n・BigQuery：膨大なデータを一瞬で分析する目玉サービス\n・Cloud Run：プログラムを置くだけで自動でサーバーを準備・実行する仕組み',
    awsExam: false,
  },

  // ── 6. 開発・アプリケーション基盤 ──────────────────────────────
  {
    id: 'd1',
    term: 'Docker（ドッカー）',
    reading: 'どっかー',
    category: '開発・アプリケーション基盤',
    description: '「コンテナ」という技術を使い、1台のサーバ上で複数のアプリがあたかも自分専用の環境があるかのように動作する仕組み。「どこでも同じ環境で動く」が最大の特徴。',
    awsExam: true,
    examPoint: 'AWSのECS（Elastic Container Service）と関連。コンテナの基礎知識として重要。',
  },
  {
    id: 'd2',
    term: 'Kubernetes（クバネティス）',
    reading: 'くばねてぃす',
    category: '開発・アプリケーション基盤',
    description: '増えすぎたアプリの「箱（コンテナ）」を自動で動かし、止まらないように管理する司令塔。Dockerコンテナを大規模に運用するためのオーケストレーションツール。「K8s」と略される。',
    awsExam: true,
    examPoint: 'AWSのEKS（Elastic Kubernetes Service）と関連。「K8s」と略される。',
  },
  {
    id: 'd3',
    term: 'GKE（Google Kubernetes Engine）',
    reading: 'じーけーいー',
    category: '開発・アプリケーション基盤',
    description: 'Google Cloudが提供する「Kubernetesのレンタル・管理サービス」。Kubernetesの設定・運用をGoogleが代わりに管理してくれる。世界最高峰のKubernetes環境を手間いらずで使えるGoogle製プラットフォーム。',
    awsExam: false,
  },
  {
    id: 'd4',
    term: 'OpenShift',
    reading: 'おーぷんしふと',
    category: '開発・アプリケーション基盤',
    description: 'Kubernetesをベースに、企業のセキュリティや開発効率を強化した「全部入り」の製品版パッケージ（Red Hat製）。\n\n「自作PC（Kubernetes）」と「メーカー製PC（OpenShift）」の関係。',
    awsExam: false,
  },
  {
    id: 'd5',
    term: 'React（リアクト）',
    reading: 'りあくと',
    category: '開発・アプリケーション基盤',
    description: 'Meta（旧Facebook）が開発した、Webサイトの見た目を作るための部品集（ライブラリ）。部品（コンポーネント）を組み合わせてUIを構築する。今流行りのフロントエンドツール。',
    awsExam: false,
  },
  {
    id: 'd6',
    term: 'Next.js（ネクスト・ジェイエス）',
    reading: 'ねくすとじぇいえす',
    category: '開発・アプリケーション基盤',
    description: 'Reactをベースにした、Webアプリを完成させるための枠組み（フレームワーク）。サーバーサイドレンダリング・静的生成などの機能を備え、本格的なWebアプリを素早く構築できる。このアプリもNext.jsで作られている。',
    awsExam: false,
  },
  {
    id: 'd7',
    term: 'Keycloak（キークローク）',
    reading: 'きーくろーく',
    category: '開発・アプリケーション基盤',
    description: 'アプリやWebサービスの「ログイン機能」や「ユーザー管理」をまとめて引き受けてくれる、オープンソースの認証・認可ツール。シングルサインオン（SSO）の実装に使われることが多い。',
    awsExam: false,
  },
  {
    id: 'd8',
    term: 'GitHub（ギットハブ）',
    reading: 'ぎっとはぶ',
    category: '開発・アプリケーション基盤',
    description: '世界中の開発者がソースコードを保存・管理・共有するためのWebサービス。変更履歴を管理し、複数人でのコード開発を可能にする「開発者の掲示板」。',
    awsExam: false,
  },
  {
    id: 'd9',
    term: 'Elasticsearch（エラスティックサーチ）',
    reading: 'えらすてぃっくさーち',
    category: '開発・アプリケーション基盤',
    description: '大量のデータの中から知りたい情報を一瞬で見つけ出す、超高性能な検索エンジン。ログ分析や全文検索に使われる。AWSではOpenSearchとして提供されている。',
    awsExam: false,
  },
  {
    id: 'd10',
    term: 'Apache Kafka（アパッチ・カフカ）',
    reading: 'かふか',
    category: '開発・アプリケーション基盤',
    description: '大量のデータをリアルタイムで、安全に、高速にやり取りするためのプラットフォーム（メッセージキュー）。IoTデータや金融取引など、大量のデータを処理するシステムで使われる。',
    awsExam: false,
  },

  // ── 7. データ分析・BI・データベース ──────────────────────────────
  {
    id: 'da1',
    term: 'データ分析の流れ（DWH）',
    reading: 'でーたぶんせき',
    category: 'データ分析・BI・データベース',
    description: 'データが業務システムからBIツールまで流れる仕組み。\n\n業務システム / 外部データ\n↓ データ収集・連携（ETL / ELT）\nデータレイク（生データをそのまま貯める）\n↓\nデータウェアハウス（DWH）（分析しやすい形に整理・統合）\n↓\nデータマート（特定目的・部門向けに切り出し）\n↓\nBI / 分析 / 機械学習',
    awsExam: false,
  },
  {
    id: 'da2',
    term: 'ETL / ELT',
    reading: 'いーてぃーえる / いーえるてぃー',
    category: 'データ分析・BI・データベース',
    description: 'データ連携の手法。\n\nETL：Extract → Transform → Load（先に加工してからDWHへ）\nELT：Extract → Load → Transform（先にDWHへ入れて、あとで加工）\n\n最近はELTが主流（DWHが高性能になったため）。',
    awsExam: true,
    examPoint: 'AWSのGlueなどのETLサービスと関連。データ移行・統合のキーワード。',
  },
  {
    id: 'da3',
    term: 'トランケート（Truncate）',
    reading: 'とらんけーと',
    category: 'データ分析・BI・データベース',
    description: 'テーブルの全データを高速に削除するSQLコマンド。DELETEよりも高速だが、ロールバック（取り消し）ができないため使用時はデータ喪失に注意が必要。',
    awsExam: false,
  },
  {
    id: 'da4',
    term: 'Snowflake / BigQuery',
    reading: 'すのーふれーく / びっぐくえりー',
    category: 'データ分析・BI・データベース',
    description: '世界中のビッグデータを飲み込む「クラウドDWH（データウェアハウス）」。\n\nSnowflake：複数クラウド対応の高性能クラウドDWH\nBigQuery：Google Cloudの分析特化型DWH。膨大なデータをSQLで瞬時に分析できる。',
    awsExam: false,
  },
  {
    id: 'da5',
    term: 'Dr.Sum',
    reading: 'どくたーさむ',
    category: 'データ分析・BI・データベース',
    description: 'ウイングアーク1st社製の国産BIツール・集計エンジン。社内のデータをパッと集計して可視化する「高性能な給水機」。日本企業向けの帳票・集計に強い。',
    awsExam: false,
  },
  {
    id: 'da6',
    term: 'Databricks（データブリックス）',
    reading: 'でーたぶりっくす',
    category: 'データ分析・BI・データベース',
    description: 'Apache Spark開発者が創設した、「データサイエンス・データエンジニアリング・機械学習のための統合データプラットフォーム」。AWS・Azure・Google Cloud上で動作する。',
    awsExam: false,
  },
  {
    id: 'da7',
    term: 'MariaDB（マリアデービー）',
    reading: 'まりあでーびー',
    category: 'データ分析・BI・データベース',
    description: 'MySQLのオリジナル開発者によって作成された、高機能でオープンソースのリレーショナルデータベース管理システム（RDBMS）。MySQLと高い互換性を持つ。',
    awsExam: false,
  },
  {
    id: 'da8',
    term: 'Tableau（タブロー）',
    reading: 'たぶろー',
    category: 'データ分析・BI・データベース',
    description: '世界で最も有名なBIツールの一つ（現在はSalesforce社の製品）。膨大なデータを視覚的に分析・共有するためのダッシュボード作成ツール。ドラッグ&ドロップで直感的に操作できる。',
    awsExam: false,
  },
  {
    id: 'da9',
    term: 'Looker（ルッカー）',
    reading: 'るっかー',
    category: 'データ分析・BI・データベース',
    description: 'Googleが買収した次世代のBIツール。LookMLというデータモデリング言語を使い、データを定義して分析する。BigQueryとの親和性が高い。',
    awsExam: false,
  },
  {
    id: 'da10',
    term: 'ThoughtSpot（トートスポット）',
    reading: 'とーとすぽっと',
    category: 'データ分析・BI・データベース',
    description: '「Googleで検索するようにデータ分析ができる」ツール。従来のBIが専門家の作ったダッシュボードを眺める形だったのに対し、誰もが自分でデータを探索できることに特化。',
    awsExam: false,
  },
  {
    id: 'da11',
    term: 'Narrative BI（ナラティブBI）',
    reading: 'ならてぃぶびーあい',
    category: 'データ分析・BI・データベース',
    description: '米国の分析プラットフォーム。HubSpotなどのデータと連携し、専門知識がなくても自動でインサイトを教えてくれるツール。データを「物語（Narrative）」として自動解説する。',
    awsExam: false,
  },

  // ── 8. AI・生成AI関連 ──────────────────────────────
  {
    id: 'ai1',
    term: 'AIエージェント',
    reading: 'えーあいえーじぇんと',
    category: 'AI・生成AI関連',
    description: '自律的に判断し、行動し、タスクを遂行するAIシステム。「指示されたことを返すAI」ではなく、目的を理解し必要な手順を自分で考えて実行する。Claude Codeはその一例。',
    awsExam: false,
  },
  {
    id: 'ai2',
    term: 'Cursor（カーソル）',
    reading: 'かーそる',
    category: 'AI・生成AI関連',
    description: 'エンジニア・非エンジニアを問わず圧倒的支持を得ているAI搭載型コードエディタ。VSCodeをベースに、AIとの対話でコードを書ける。Claude CodeやGitHub Copilotと似た位置づけ。',
    awsExam: false,
  },
  {
    id: 'ai3',
    term: 'Dify',
    reading: 'でぃふぁい',
    category: 'AI・生成AI関連',
    description: 'LLM（大規模言語モデル）アプリケーションを簡単に開発・運用できるオープンソースのプラットフォーム。コードをほとんど書かずにAIアプリケーションを構築できる。',
    awsExam: false,
  },
  {
    id: 'ai4',
    term: 'DeFi（ディファイ／分散型金融）',
    reading: 'でぃふぁい',
    category: 'AI・生成AI関連',
    description: 'Decentralized Finance。銀行や証券会社などの中央管理者（仲介者）を介さず、ブロックチェーン上で行われる金融サービス。透明性の高い「稼ぐ・守る」ためのインフラ。\n\n※AIではなくブロックチェーン技術の用語。',
    awsExam: false,
  },
  {
    id: 'ai5',
    term: 'BHQ（Brain Healthcare Quotient）',
    reading: 'びーえいちきゅー',
    category: 'AI・生成AI関連',
    description: '脳の健康度を数値化・指標化したもの。AIや健康テック分野での活用が期待されている指標。',
    awsExam: false,
  },
]

// IDで用語を検索する関数
export function getTermById(id: string): Term | undefined {
  return terms.find((t) => t.id === id)
}
